myproject/michFit/urls.py
from django.urls import path

from . import views


app_name = 'michFit'
urlpatterns = [
    path('', views.home, name='home'),
    path('cart_add/<item_id>/',views.cart_add, name='cart_add'),
    path('cart/view/<item_id>/',views.cart_view, name='cartview'),
    path('cartdelete/<item_id>/',views.cartdelete, name='cartdelete'),
    path('sendemail/',views.send_email,name='sendemail')
]

myproject/myproject/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('michFit/', include('michFit.urls') ),
    path('',include('michFit.urls'))
]

myproject/michFit/models.py
from django.db import models
from . import calorieCounter

# Create your models here.
class ItemManager(models.Manager):
    def create_item(self,name,calories,protein):
        item = self.create(name=name, calories = calories, protein=protein)
        return item

class MenuItem(models.Model):
    name = models.CharField(max_length = 200)
    calories = models.IntegerField()
    protein = models.CharField(max_length=10)
    objects=ItemManager()

myproject/michFit/forms.py
from django import forms
PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 10)]


class CartAddProductForm(forms.Form):
    quantity = forms.TypedChoiceField(choices=PRODUCT_QUANTITY_CHOICES, coerce=int)
    update = forms.BooleanField(required=False, initial=False, widget=forms.HiddenInput)

myproject/michFit/views.py
from django.shortcuts import render
import smtplib

from django.http import HttpResponse, Http404
from .models import MenuItem
from . import calorieCounter
cart = []
totalCalories = 0
totalProtein = 0
def home(request):
    menu = MenuItem.objects.all()
    context = {'menu': menu}
    MenuItem.objects.all().delete()
    for key, value in calorieCounter.itemsDict.items():
        MenuItem.objects.create_item(key, value[0],value[1])
    return render(request,'michFit/index.html',context)


def cartdelete(request, item_id):
    try:
        print(cart)
        cart.remove(MenuItem.objects.get(pk=item_id))
        totalCalories = 0
        totalProtein=0
        for item in cart:
            totalCalories += item.calories
            totalProtein+=item.protein
        return render(request, 'michFit/cart.html',{'cart': cart, 'totalCalories': totalCalories, 'totalProtein': totalProtein} )
    except:
        print(cart)
        totalCalories = 0
        totalProtein=0
        for item in cart:
            totalCalories += item.calories
            totalProtein+=item.protein
        return render(request, 'michFit/cart.html',{'cart': cart, 'totalCalories': totalCalories, 'totalProtein': totalProtein} )
    

def cart_add( request,item_id):
    cart.append(MenuItem.objects.get(pk=item_id))
    menu = MenuItem.objects.all()
    context = {'menu': menu}
    return render(request,'michFit/index.html',context)
    
    
   
    
def cart_view(request,item_id):

    totalCalories = 0
    totalProtein=0
    for item in cart:
        totalCalories += item.calories
        totalProtein+=item.protein
    return render(request, 'michFit/cart.html',{'cart': cart, 'totalCalories': totalCalories, 'totalProtein': totalProtein} )

def send_email(request):
    print('send email view')
    names=[]
    for item in cart:
        names.append(item.name)
    print(names)
    smtpObj = smtplib.SMTP('smtp.gmail.com',587)
    print('smtplib.SMTP')
    smtpObj.ehlo()
    print('smtpObj.ehlo')
    smtpObj.starttls()
    print('starttls')
    smtpObj.login('tkamoua@gmail.com',input())

    print('Login success')
    smtpObj.sendmail('tkamoua@gmail.com','tkamoua@umich.edu','Subject: Menu. \n\n %s' %(names))
    print('sent email')
    smtpObj.quit()
    return HttpResponse("Email sent")

myproject/michFit/templates/michFit/cart.html
  {% load static %}
  <!DOCTYPE html>
<html>

<head>
  <meta charset="utf-8">
  <title></title>
  <meta name="author" content="">
  <meta name="description" content="">
  <meta name="viewport" content="width=device-width, initial-scale=1">



<link rel="stylesheet" type="text/css" href="{% static 'michFit/style.css' %}">
</head>

<body>

<h1 class="text-center"><a class="cart white" href = "{% url 'michFit:home'  %}">Home</a></h1>
<h1 class="white text-center">Cart</h1>


    {% if cart %}
    <ul class="ulcart">

    {% for item in cart %}
        <li class="black"><strong>{{ item.name }}</strong>   Calories: {{ item.calories}} Protein: {{item.protein}} <a href="{% url 'michFit:cartdelete' item.id %}"><button>Delete Item</button></a> </li>
    {% endfor %}
   <h2 class="black">Calories: {{totalCalories}} </h2>
   <h2 class="black">Protein: {{totalProtein}}</h2>
    </ul>
{% else %}
    <p class="black text-center">Empty Cart</p>
{% endif %}

<a href="{% url 'michFit:sendemail'%}"><button>Send to Email</button></a>
    



  <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.4/jquery.min.js"></script>

</body>

</html>

myproject/michFit/templates/michFit/index.html
  {% load static %}
  <!DOCTYPE html>
<html>

<head>
  <meta charset="utf-8">
  <title></title>
  <meta name="author" content="">
  <meta name="description" content="">
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <link href="https://fonts.googleapis.com/css?family=Roboto&display=swap" rel="stylesheet">

<link rel="stylesheet" type="text/css" href="{% static 'michFit/style.css' %}">
</head>

<body>
    <div class="container">
        <h1 class="text-center">Todays Menu (Mojo)</h1>
        {% if menu %}
          <ul class="text-center">
          {% for item in menu %}
              <li><a class="black" href="{% url 'michFit:cart_add' item.id %}"><strong>{{ item.name }}</strong>   Calories: {{ item.calories}} Protein: {{item.protein}} </a></li>
          {% endfor %}
          </ul>
      {% else %}
          <p>No food today.</p>
      {% endif %}
      
      <h2 class="text-center "><a class="cart" href="{% url 'michFit:cartview' 0 %}">View Cart</a></h2>
    </div>


  <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.4/jquery.min.js"></script>

</body>

</html>